### ISSUE TITLE
Not able to download data

### ISSUE THREAD

**Issue by krishvishal** [applicaai/kleister-charity#1]
I'm getting `connection refused` error for all files when I run the `./annex-get-all-from-s3.sh
`.  

Sample error trace:
```
get documents/2b8fb695f863b80a6ecc56bb24bde8d2.pdf (from pub-aws-s3...)
failed: Connection refused.
failed
get documents/2b96849e811f274e6754ba83380f7e9a.pdf (from pub-aws-s3...)
failed: Connection refused.
failed
get documents/2b9bdd141182347e4e522754bfad951a.pdf (from pub-aws-s3...)
failed: Connection refused.

```

Can you please fix this?

**Comment by t-haotzh** [comment]
I got the same problem, could you please double check it? Thank you!

**Comment by madisonmay** [comment]
Also chiming in to say I'm unable to pull the source documents

**Comment by tstanislawek** [comment]
@krishvishal @t-haotzh @madisonmay 

Sorry for late answer, for now please download the dataset from this link: https://drive.google.com/file/d/13kej-Mm5-U2Lcz0UHb9NZkkHljGXWCUC/view?usp=sharing 

I will try to fix the problem in the repository.

**Comment by madisonmay** [comment]
Many thanks @tstanislawek! Would you be the best point of contact to reach out to re: credentials for running against test splits as well?

**Comment by tstanislawek** [comment]
I actually put [exptected.tsv](https://github.com/applicaai/kleister-charity/blob/master/test-A/expected.tsv) file for test set, so you could easily evaluate your solutions.

Write me a message if you have some other problems.

**Comment by madisonmay** [comment]
Huge thanks... I think that's all I needed!  Seems like a simpler solution than the geval / gonito option for sure.

**Comment by Daemon-ser** [comment]
> @krishvishal @t-haotzh @madisonmay
> 
> Sorry for late answer, for now please download the dataset from this link: https://drive.google.com/file/d/13kej-Mm5-U2Lcz0UHb9NZkkHljGXWCUC/view?usp=sharing
> 
> I will try to fix the problem in the repository.

Hi, the shared link is expired

**Comment by paulpaul91** [comment]
> https://drive.google.com/file/d/13kej-Mm5-U2Lcz0UHb9NZkkHljGXWCUC/view?usp=sharing

not exist?

**Comment by tstanislawek** [comment]
@paulpaul91 / @Daemon-ser
I have created new link: https://drive.google.com/file/d/1doNZ9iulC9hdcEfUhG91whNajXMJrog7/view?usp=sharing

Sorry for late answer.
