### ISSUE TITLE
What is the license of this dataset?

### ISSUE THREAD

**Issue by zeyuanchen23** [applicaai/kleister-charity#2]
What is the license of this dataset? Is commercial use allowed?

**Comment by tstanislawek** [comment]
The data was downloaded from this page [link](https://www.gov.uk/government/organisations/charity-commission) so the license is [open-government-licence](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/)

**Comment by zeyuanchen23** [comment]
Thanks for the explanation!
